### ISSUE TITLE
能否增加对图片等更多消息内容的支持

### ISSUE THREAD

**Issue by PackageInstaller** [molanp/nonebot_zhenxun_plugin_bottle#1]
如题，隔壁nonebot有个类似的插件，支持的内容很多，作者可以参考下
https://github.com/Todysheep/nonebot_plugin_bottle

**Comment by molanp** [comment]
是有这个代办的，目前正在找获取图片和文字的接口

**Comment by molanp** [comment]
已支持图片和小emoji，超级表情不受支持
00718486c90968ea38bffee75398b2aec095f8a5
